### ISSUE TITLE
感觉语句不通顺 --> 在 Collections 框架中不可能将任何方便实现类子类化。

### ISSUE THREAD

**Issue by zhoujin7** [sjsdfg/effective-java-3rd-chinese#12]
https://sjsdfg.github.io/effective-java-3rd-chinese/#/notes/01.%20%E8%80%83%E8%99%91%E4%BD%BF%E7%94%A8%E9%9D%99%E6%80%81%E5%B7%A5%E5%8E%82%E6%96%B9%E6%B3%95%E6%9B%BF%E4%BB%A3%E6%9E%84%E9%80%A0%E6%96%B9%E6%B3%95
在 Collections 框架中不可能将任何方便实现类子类化。

谷歌翻译:
it is impossible to subclass any of the convenience implementation classes in the Collections Framework. 
无法在集合框架中**继承**任何~~便捷~~实现类。

**Comment by sjsdfg** [comment]
就需要你这种读者，多提提意见吧

**Comment by sjsdfg** [comment]
如果能直接发起 PR 就更好了

**Comment by zhoujin7** [comment]
> 如果能直接发起 PR 就更好了

好咯
