### ISSUE TITLE
错别字、翻译错误

### ISSUE THREAD

**Issue by jgben12** [sjsdfg/effective-java-3rd-chinese#17]
docs/notes/18. 组合优于继承.md
……但是，一旦父类增加了这样的新方法，则**很有肯能**由于调用了未被重写的新方法，将非法的元素添加到子类的实例中。这不是个纯粹的理论问题。……
59. 了解并使用库
……有几个图书馆（library）值得一提……

**Comment by sjsdfg** [comment]
Effective Java 第三版翻译校对群：909059971
