### ISSUE TITLE
26条翻译问题

### ISSUE THREAD

**Issue by hailianglone** [sjsdfg/effective-java-3rd-chinese#32]
不可否认的是，这个错误信息留下了一些需要的东西，但是编译器已经完成了它的工作，不管它的元素类型是什么，都不会破坏集合的类型不变性。 **你不仅可以将任**何元素（除 null 以外）放入一个 Collection<?> 中，但是不能保证你所得到的对象的类型。 如果这些限制是不可接受的，可以使用泛型方法（详见第 30 条）或有限制配符类型（详见第 31 条）。

你不仅不能将任何元素（除 null 之外）放入 Collection<?>，而且不能臆想你得到的对象的类型

**Comment by sjsdfg** [comment]
感谢,希望多提意见。翻译已经修正
