### ISSUE TITLE
第17条翻译太硬了...

### ISSUE THREAD

**Issue by ukyo6** [sjsdfg/effective-java-3rd-chinese#34]
### 类型

2. 翻译校对

### 校正条目

- 第 17 条

### 校正内容

- 英语原文（翻译校对时使用）：
It was not widely understood that immutable classes had to be effectively final when BigInteger and BigDecimal were written, so all of their methods may be overridden
- 翻译原文：
当 BigInteger 和 BigDecimal 被写入时，不可变类必须是有效的 final，因此它们的所有方法都可能被重写。

- 校对之后的内容：
当BigInteger 和 BigDecimal 被编写出来的时候, 不可变类必须为final还没有得到广泛理解, 因此他们的所有方法都可能被重写.

**Comment by sjsdfg** [comment]
感谢给出的意见。优化了部分翻译。

更多的还是要看你们的帮助
