### ISSUE TITLE
【标点符号校对】条目45. 明智审慎地使用 Stream

### ISSUE THREAD

**Issue by crc1993** [sjsdfg/effective-java-3rd-chinese#35]
### 类型

1. 标点符号

### 校正条目

- 第四段

### 校正内容

- 翻译原文：Stream API 流式的（fluent）：:它设计允许所有组成管道的调用被链接到一个表达式中。事实上，多个管道可以链接在一起形成一个表达式。
- 校对之后的内容：Stream API 流式的（fluent）：它设计允许所有组成管道的调用被链接到一个表达式中。事实上，多个管道可以链接在一起形成一个表达式。

**Comment by sjsdfg** [comment]
感觉这句话第一句也没对上，，应该是流式的 Stream API
