### ISSUE TITLE
在每篇文章后面加个换行，合并文件的时候粘在一起了，如：test#50.必要时xx

### ISSUE THREAD

**Issue by mr-dragon** [sjsdfg/effective-java-3rd-chinese#4]
在每篇文章后面加个换行
方便使用cat命令合并成一个文件的时候不会影响目录的生成
(如：test#50. 必要时进行防御性拷贝    黏合在一起了,markdown 编辑器识别不了)
谢~

**Comment by sjsdfg** [comment]
你修改之后提交一个 pr 吧

**Comment by mr-dragon** [comment]
> 你修改之后提交一个pr吧

给个权限~
