### ISSUE TITLE
【错别字校对】条目18组合优于继承

### ISSUE THREAD

**Issue by liyiye012** [sjsdfg/effective-java-3rd-chinese#45]
### 类型

1. 错别字

### 校正条目

- 第18 条组合优于继承

### 校正内容

- 英语原文（翻译校对时使用）：
 It amounts to reimplementing superclass methods that may or may not result in self-use, which is difficult, time-consuming, error-prone, and may reduceperformance.
- 翻译原文：
这相当于重新实现了父类方法，这样的方法可能不能确定到底是否**时**自用（self-use）的，实现起来也是困难的，耗时的，容易出错的，并且可能会降低性能。 
- 校对之后的内容：
这相当于重新实现了父类方法，这样的方法可能不能确定到底是否**是**自用（self-use）的，实现起来也是困难的，耗时的，容易出错的，并且可能会降低性能。

**Comment by sjsdfg** [comment]
可以学一下如何提交 PR。

提交 pr 比提 issue 更加高效

**Comment by liyiye012** [comment]
> 可以学一下如何提交 PR。
> 
> 提交 pr 比提 issue 更加高效

好的，谢谢

**Comment by sjsdfg** [comment]
> > 可以学一下如何提交 PR。
> > 提交 pr 比提 issue 更加高效
> 
> 好的，谢谢

https://www.bilibili.com/video/av58040840/ 这是我录制过的一个如何提交 PR 的视频。

但是 github 本身有更简单的方式
